### ISSUE TITLE
Docker Image not working

### ISSUE THREAD

**Issue by JeremyBYU** [r9y9/PCL.jl#22]
Hi, I was just attempting to try out your project using the docker image. I followed your instruction here

```
docker pull r9y9/julia-cxx
docker run -it --rm r9y9/julia-cxx:PCL
```
Then I attempted to import your package and received this error.

```
julia> using PCL
INFO: Precompiling module Reexport.

signal (4): Illegal instruction
while loading /root/.julia/v0.6/PCLIO/src/PCLIO.jl, in expression starting on line 28
unknown function (ip: 0x7efb9ecad0c4)
unknown function (ip: 0x7efb9ecadddb)
unknown function (ip: 0x7efb9ecad3c3)
unknown function (ip: 0x7efb9ecad168)
unknown function (ip: 0x7efb9ecab5c2)
unknown function (ip: 0x7efb9ecab56c)
anonymous at ./<missing> (unknown line)
unknown function (ip: 0x7efb9ecab54f)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_toplevel_eval_flex at /julia/src/toplevel.c:630 [inlined]
jl_toplevel_eval at /julia/src/toplevel.c:641
jl_toplevel_eval_in_warn at /julia/src/builtins.c:590
RunGlobalConstructors at /root/.julia/v0.6/Cxx/src/initialization.jl:63
ParseToEndOfFile at /root/.julia/v0.6/Cxx/src/initialization.jl:109
ParseVirtual at /root/.julia/v0.6/Cxx/src/initialization.jl:138
unknown function (ip: 0x7efb9ec7cc9d)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
macro expansion; at /root/.julia/v0.6/Cxx/src/cxxstr.jl:662 [inlined]
anonymous at ./<missing> (unknown line)
unknown function (ip: 0x7efb9ecab50f)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_toplevel_eval_flex at /julia/src/toplevel.c:630
jl_eval_module_expr at /julia/src/toplevel.c:196
jl_toplevel_eval_flex at /julia/src/toplevel.c:526
jl_toplevel_eval_flex at /julia/src/toplevel.c:594
jl_parse_eval_all at /julia/src/ast.c:735
jl_load at /julia/src/toplevel.c:657
jl_load_ at /julia/src/toplevel.c:666
include_from_node1 at ./loading.jl:541
unknown function (ip: 0x7efda51316bb)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
do_call at /julia/src/interpreter.c:66
eval at /julia/src/interpreter.c:205
jl_toplevel_eval_flex at /julia/src/toplevel.c:619 [inlined]
jl_toplevel_eval at /julia/src/toplevel.c:641
jl_toplevel_eval_in_warn at /julia/src/builtins.c:590
eval at ./boot.jl:234
unknown function (ip: 0x7efda511cc5f)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
require at ./loading.jl:446
unknown function (ip: 0x7efda5175bdb)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
jl_apply at /julia/src/julia.h:1364 [inlined]
eval_import_path_ at /julia/src/toplevel.c:463
eval_import_path at /julia/src/toplevel.c:490 [inlined]
jl_toplevel_eval_flex at /julia/src/toplevel.c:541
jl_toplevel_eval_flex at /julia/src/toplevel.c:594
jl_eval_module_expr at /julia/src/toplevel.c:196
jl_toplevel_eval_flex at /julia/src/toplevel.c:526
jl_toplevel_eval_flex at /julia/src/toplevel.c:594
jl_parse_eval_all at /julia/src/ast.c:735
jl_load at /julia/src/toplevel.c:657
jl_load_ at /julia/src/toplevel.c:666
include_from_node1 at ./loading.jl:541
unknown function (ip: 0x7efda51316bb)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
do_call at /julia/src/interpreter.c:66
eval at /julia/src/interpreter.c:205
jl_toplevel_eval_flex at /julia/src/toplevel.c:619 [inlined]
jl_toplevel_eval at /julia/src/toplevel.c:641
jl_toplevel_eval_in_warn at /julia/src/builtins.c:590
eval at ./boot.jl:234
unknown function (ip: 0x7efda511cc5f)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
require at ./loading.jl:446
unknown function (ip: 0x7efda5175bdb)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
jl_apply at /julia/src/julia.h:1364 [inlined]
eval_import_path_ at /julia/src/toplevel.c:463
eval_import_path at /julia/src/toplevel.c:490 [inlined]
jl_toplevel_eval_flex at /julia/src/toplevel.c:541 [inlined]
jl_toplevel_eval at /julia/src/toplevel.c:641
jl_toplevel_eval_in_warn at /julia/src/builtins.c:590
eval at ./boot.jl:234
unknown function (ip: 0x7efda511cc5f)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
eval_user_input at ./REPL.jl:66
unknown function (ip: 0x7efb9ec5fd86)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
macro expansion at ./REPL.jl:97 [inlined]
#3 at ./event.jl:68
unknown function (ip: 0x7efb9ec58e5f)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
jl_apply at /julia/src/julia.h:1364 [inlined]
start_task at /julia/src/task.c:259
unknown function (ip: 0xffffffffffffffff)
Allocations: 4677350 (Pool: 4676280; Big: 1070); GC: 6
Illegal instruction (core dumped)
```
Just a note, it its running Julia .6-dev, not sure if thats an issue.  Also if we  get this working, will I need to use nvidia-docker to run the graphics for visualization? Or is the CPU just fine for handling displaying of graphics. Thanks!

**Comment by JeremyBYU** [comment]
A little more prodding shows that the Julia pacakge for Cxx doesnt seem to be working in the docker container.

```
julia> using Cxx

C++ > #include <iostream>
signal (4): Illegal instruction
while loading no file, in expression starting on line 0
unknown function (ip: 0x7f65f68fa771)
unknown function (ip: 0x7f65f68fa503)
unknown function (ip: 0x7f65f68fa4a9)
unknown function (ip: 0x7f65f68fa483)
unknown function (ip: 0x7f65f68f8b63)
unknown function (ip: 0x7f65f68f8968)
unknown function (ip: 0x7f65f68f88ec)
isExpressionComplete at /root/.julia/v0.6/Cxx/src/CxxREPL/replpane.jl:129
#4 at /root/.julia/v0.6/Cxx/src/CxxREPL/replpane.jl:194
unknown function (ip: 0x7f65f68f86e2)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
on_enter at ./LineEdit.jl:1267
unknown function (ip: 0x7f67fcd9bf6b)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
#92 at ./LineEdit.jl:1351
#13 at ./LineEdit.jl:736
unknown function (ip: 0x7f65f68e9932)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
prompt! at ./LineEdit.jl:1605
run_interface at ./LineEdit.jl:1574
unknown function (ip: 0x7f67fcd9ec8f)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
run_frontend at ./REPL.jl:931
run_repl at ./REPL.jl:190
unknown function (ip: 0x7f65f68bb4b2)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
_start at ./client.jl:368
unknown function (ip: 0x7f67fcdba178)
jl_call_method_internal at /julia/src/julia_internal.h:185 [inlined]
jl_apply_generic at /julia/src/gf.c:1944
unknown function (ip: 0x401a8d)
unknown function (ip: 0x401396)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4013da)
Allocations: 3918808 (Pool: 3917746; Big: 1062); GC: 4
Illegal instruction (core dumped)
```

**Comment by r9y9** [comment]
I'm afraid I cannot reproduce. Just a guess, but you might be runining on a non x86_64 architecture? The julia in the docker image is built for x86_64 (https://github.com/r9y9/julia-cxx/blob/74789cff79534a34cf47ee06e501f810df4527f6/ubuntu14.04/Dockerfile#L52).

>  it its running Julia .6-dev, not sure if thats an issue. Also if we get this working, will I need to use nvidia-docker to run the graphics for visualization? Or is the CPU just fine for handling displaying of graphics. 

0.5.x (with patched jitlayers.cpp), 0.6 and 0.7-dev should be ok. CPU is just fine for visualization, but I haven't test it with the docker image. I'd recommend you build it yourself if you want visualization features.

**Comment by r9y9** [comment]
> Just a guess, but you might be runining on a non x86_64 architecture? 

Never mind, julia won't run on non x86_64 architecture if it's built for x86_64.

**Comment by JeremyBYU** [comment]
Thanks for the reply. I actually tested it on two computers and got the
same error. Both had docker installed and are x64. I spent a couple hours
trying to figure it out, but I'm pretty sure it has to do with Cxx. The Cxx
julia docker image (which pcl image extends from) didn't work as well when
testing. I'll keep plugging away at it though because this package looks
way to good to give up this early.

I'll let you know if I find anything else. PS host computers are Ubuntu
16.04 and one is 16.10. one is a Skylake processor and other is some xeon
cpu.

**Comment by JeremyBYU** [comment]
Just and update.  I tried to manually install your Cxx libarary in a vanilla docker Ubuntu 14.04 container.  I followed all the steps from your docker file exactly.  It took a *long* time to compile Julia but it eventually finished. I also downloaded your fork of Cxx.  One thing to note however. This step in the [docker file](https://github.com/r9y9/julia-cxx/blob/master/ubuntu14.04/Dockerfile#L64-L65) where you check out a specific commit, does not exist (commit HASH `3f99d56476054241d3c00f331d6377284773367f`), at least it complained it didn't exist.  However it seems like the branch `r9y9` is the default branch and the commit `f72787f8f2dcc8c43a831bb1cbdb5cda72cf4af8` is the default one with your fix for RTTI.  So I just built from that.  I tried to run Cxx and the same errors as above occurred with an illegal exception.

So I thought I would try one more thing.  I have a third computer that is a Windows 10 computer (broadwell processor).  I installed docker (its a little different than Linux because it actually runs a VM in the background) on it and ran your docker PCL image.  It worked! No issues at all. 

So...It seems that the issue is really nothing to do with your docker file, just something really crazy that doesn't work on my two Linux computers.  I'm thinking something to do with building Julia or building Cxx on my computers causes some serious issues where illegal instructions are being generated.  Not sure what to do next, but I'll see what else I can do to figure this out. 

Oh one last thing.  I have Julia installed locally on those 2 Linux computers (not through docker) using Julia Pro (0.5.1 julia version). I decided to see if I could run Keno's Cxx library on these computers.  I installed it and there were no issues calling and running C++.  So it should defenitely be possible for me to run your project on these Linux computers.  I just would really prefer to to use Docker.

**Comment by r9y9** [comment]
Thank you very much for investigating. Yes, building entire dependencies takes too long time and hard, so I created the docker image. 

> This step in the docker file where you check out a specific commit, does not exist (commit HASH 3f99d56476054241d3c00f331d6377284773367f),

Sorry about that. This is because I rebased against Keno's master to cleanup history. Maybe I should use merge instead.

> Oh one last thing. I have Julia installed locally on those 2 Linux computers (not through docker) using Julia Pro (0.5.1 julia version). I decided to see if I could run Keno's Cxx library on these computers. I installed it and there were no issues calling and running C++. So it should defenitely be possible for me to run your project on these Linux computers. I just would really prefer to to use Docker.

To be honest, I'm not quite familar with docker, so I might not be able to help you much. Anyway since julia-cxx hasn't been updated for months, let me update it for newer stable julia release (0.5.2) and latest Cxx.

**Comment by JeremyBYU** [comment]
Thanks again for your help and responses.

> To be honest, I'm not quite familar with docker

You could have fooled me, the docker set up seems to be solid.

> Anyway since julia-cxx hasn't been updated for months, let me update it for newer stable julia release (0.5.2) and latest Cxx.

Yeah that's the next thing I'm going to try as well. Maybe they had a fix for this situation. I'll update you later on any progress.

**Comment by JeremyBYU** [comment]
Happy Update!  I now have Julia, PCL, and Cxx working in a docker container.  Here are the **different** steps that I took  (everything not mentioned is the exact same as your docker build):

1. I started with a clean ubuntu:14.04 container
2. I downloaded the current stable binary release of Julia (0.5.2). I extracted it to the same directory as expected in you docker build: `/julia/usr`. 
3. I saw that you had already updated your fork of Cxx so I simply downloaded and had Julia build from the `r9y9` branch.

After that everything worked.  So to me this means that it was either a bug in Cxx that got fixed upstream, or there was something wrong with building Julia from that specific .6-dev commit. 

FYI the visualization did not work out of the box for me.  Even with passing over my x-sever session there were issues because I have a dedicated nvidia graphics card with my intel graphics disabled.  Because of this I needed to run a slightly modified image using [nvidia-docker](https://github.com/NVIDIA/nvidia-docker).  If anyone ever is interested you can follow instructions [here](http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration).

![image](https://cloud.githubusercontent.com/assets/6628085/26279711/dc64cf7c-3d88-11e7-8255-692a8c4e8221.png)

Thanks again for all your help! Do you think we should update your docker build to use the latest stable release of Julia (forgo building julia) and updated the commit HASH of julia-cxx to use your latest one? I can do this work in a fork for you if you like. Thanks!

**Comment by r9y9** [comment]
Great! I'm glad to hear that.

Unfortunately, binary release of Julia 0.5.2 is not enough. It needs https://github.com/r9y9/julia-cxx/blob/74789cff79534a34cf47ee06e501f810df4527f6/ubuntu14.04/jitlayers.patch to pass all tests in PCL.jl, without the patch almost works though. I'm building the docker images now.

> Do you think we should update your docker build to use the latest stable release of Julia (forgo building julia) and updated the commit HASH of julia-cxx to use your latest one? I can do this work in a fork for you if you like. Thanks!

Yes, I'll push a new one based on julia 0.5 and Cxx master. Any improvements other than that (e.g. visualization fixes, etc) would be very welcome!

**Comment by r9y9** [comment]
Ok, pushed. https://hub.docker.com/r/r9y9/julia-cxx/tags/

**Comment by JeremyBYU** [comment]
Awesome, I tried out your new container (PCL) and everything seemed to work the same as my docker container.  I ran the tests and got the following:
```
julia> Pkg.test("PCL")
INFO: Testing PCL
Cloud before filtering
    0.06872353 0.64002645 0.1882799
    0.6037358 -0.5924739 -1.4134667
    0.8469611 -0.4360672 -0.20045792
    -0.18040742 0.73905283 -1.3438088
    -0.44348446 0.9636045 0.29803377
Cloud after filtering
    0.06872353 0.64002645 0.1882799
    -0.44348446 0.9636045 0.29803377
Test Summary: | 
  passthrough | No tests
INFO: Normal estimation
INFO: Uniform sampling
Model total points: 12575; Selectd Key points: 193
Scene total points: 307200; Selectd Key points: 7739
INFO: Associating a 3D descriptor to each model and scene keypoint
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 5807
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 5837
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 6170
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 7297
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 6214
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 7354
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 7436
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 7488
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 7550
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 6670
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 5612
INFO: Find Model-Scene Correspondences with KdTree
length(model_scene_corrs) = 3400
INFO: Clustering
length(rototranslations) = 8
i = 0
i = 1
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
INFO: ICP
Instance 0 Aligned!
Instance 1 Aligned!
Instance 2 Aligned!
Instance 3 Aligned!
Instance 4 Aligned!
Instance 5 Aligned!
Instance 6 Aligned!
Instance 7 Aligned!
Occlusion cloud not set, using scene_cloud instead...
Computing cues took 68ms.
Computing clutter cues took 0ms.
SA search... took 43ms.
Instance 0 is bad!
Instance 1 is bad!
Instance 2 is bad!
Instance 3 is bad!
Instance 4 is bad!
Instance 5 is good!
Instance 6 is bad!
Instance 7 is bad!
Test Summary:                  | 
  global_hypothesis_verification | No tests
PointCloud before filtering: 460400 data points
PointCloud before filtering: 41049 data points
Test Summary: | 
  voxel_grid  | No tests
INFO: Normal estimation
INFO: Uniform sampling
Model total points: 12575; Selectd Key points: 686
Scene total points: 307200; Selectd Key points: 3747
INFO: Associating a 3D descriptor to each model and scene keypoint
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 2991
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 2993
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 3109
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 3123
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 3706
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 2712
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 3717
INFO: Find Model-Scene Correspondences with KdTree
length(model_scene_corrs) = 1777
INFO: Clustering
length(rototranslations) = 1
Test Summary:           | 
  correspondence_grouping | No tests
Point cloud data: 15 points
x,y,z: -0.9489802,0.93606704,2.0
x,y,z: -0.3437455,-0.38999134,1.0
x,y,z: -0.6442083,1.0298296,1.0
x,y,z: -1.0676087,-0.32435745,-2.0
x,y,z: -0.38646188,-0.84192026,1.0
x,y,z: 1.0686294,1.8438306,1.0
x,y,z: 0.7754149,-0.26972428,4.0
x,y,z: 0.7506673,-2.1884146,1.0
x,y,z: -0.52038544,2.7754045,1.0
x,y,z: -1.7954012,-1.0127441,1.0
x,y,z: 0.13636032,0.98010564,1.0
x,y,z: 0.94960845,0.74482495,1.0
x,y,z: 0.16885003,-0.68254954,1.0
x,y,z: -0.59394556,0.18732007,1.0
x,y,z: 0.8637243,-0.9197366,1.0
Model Coefficients: 0.0 0.0 1.0 -1.0 
Model inliers: 12
0  x,y,z: -0.3437455,-0.38999134,1.0
1  x,y,z: -0.6442083,1.0298296,1.0
2  x,y,z: -0.38646188,-0.84192026,1.0
3  x,y,z: 1.0686294,1.8438306,1.0
4  x,y,z: 0.7506673,-2.1884146,1.0
5  x,y,z: -0.52038544,2.7754045,1.0
6  x,y,z: -1.7954012,-1.0127441,1.0
7  x,y,z: 0.13636032,0.98010564,1.0
8  x,y,z: 0.94960845,0.74482495,1.0
9  x,y,z: 0.16885003,-0.68254954,1.0
10  x,y,z: -0.59394556,0.18732007,1.0
11  x,y,z: 0.8637243,-0.9197366,1.0
Test Summary:       | 
  planar_segmentation | No tests
  2.565200 seconds (2.57 k allocations: 114.941 KB)
PointCloud before filtering: 460400 data points
PointCloud before filtering: 451410 data points
Test Summary:       | 
  statistical_removal | No tests
length(cloud) = 307200
convert(Int,length(clusters)) = 22
Test Summary:                   | 
  region_growing_rgb_segmentation | No tests
PointCloud before filtering: 460400 data points
PointCloud after filtering: 41049 data points
PointCloud representing the planar component:20161 data points
PointCloud representing the planar component:12114 data points
Test Summary:   | 
  extract_indices | No tests
PointCloud representing the planar component:60149 data points
ground_normal = Float32[-0.593471,0.0427265,0.803721]
rotation = Float32[-0.0427265,-0.593471,0.0]
theta = -0.6372743f0
rad2deg(theta) = -36.513126f0
  0.804733  0.0140581   0.593471          0
 0.0140581   0.998988 -0.0427265          0
 -0.593471  0.0427265   0.803721          0
         0          0          0          1
estimated_distance = 2571.423000068314
Test Summary:     | 
  tilt_compensation | No tests
  0.037905 seconds (3.35 k allocations: 148.855 KB)
length(clusters) = 2
Test Summary:      | 
  cluster_extraction | No tests
INFO: PCL tests passed
```

As you can see some tests don't exactly pass.  This is the *exact* same for me when using the unpatched release version on my docker container.  Don't know if it really matters. I can make a pull request providing a docker image that can be used by nvidia-docker and also write some documentation (allows ability to use discrete graphics for visualization and the possibility of using CUDA).
